server:
    port: 8888
spring:
    cloud:
        config:
            server:
                native:
                    searchLocations: /usr/local/lib/config
    profiles:
        active: native
management:
    endpoints:
        web:
            exposure:
                include: health